In [4]:
import pandas as pd
def LoadAllData(path):
    events_battle = pd.read_csv(path + 'events_battle.txt',sep=",")
    events_hero = pd.read_csv(path + 'events_hero.txt',sep=",")
    events_level = pd.read_csv(path + 'events_level.txt',sep=",")
    events_payment = pd.read_csv(path + 'events_payment.txt',sep=",")
    events_quest = pd.read_csv(path + 'events_quest.txt',sep=",")
    events_resource = pd.read_csv(path + 'events_resource.txt',sep=",")
    events_user = pd.read_csv(path + 'events_user.txt',sep=",")
    return events_battle, events_hero, events_level, events_payment, events_quest, events_resource, events_user

In [5]:
events_battle, events_hero, events_level, events_payment, events_quest, events_resource, events_user = LoadAllData(r'data/')

In [6]:
events_battle.describe()

,id,duration,ai_share,experience,crystals,mana
count,2.144030e+05,214403.000000,214403.000000,214403.000000,214403.000000,214403.000000
mean,5.429205e+05,54839.866457,0.942926,1291.095069,-0.002668,10.000956
std,2.787625e+05,32970.913699,0.229228,8377.639765,0.263571,7.842348
min,8.706000e+03,0.000000,0.000000,0.000000,-20.000000,0.000000
25%,3.990135e+05,33154.000000,1.000000,5.000000,0.000000,0.000000
50%,5.580610e+05,46911.000000,1.000000,11.000000,0.000000,10.000000
75%,7.353220e+05,67349.000000,1.000000,76.000000,0.000000,15.000000
max,1.047966e+06,680022.000000,1.000000,427012.000000,12.000000,45.000000